# -*- coding: utf-8 -*-
"""Copia de TFM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tIk3rH5yYyhqv-D7z0FVQK7aFsZpqjD

"""
import logging
import os
import json
import pandas as pd
import numpy as np
from pymongo import MongoClient
from sklearn.ensemble import IsolationForest
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas
import time
import sys # Importar sys para StreamHandler a stderr
import glob # Importar glob para buscar archivos por patrón

# ============================================================================
#                          CONFIGURACIÓN GLOBAL
# ============================================================================
from dotenv import load_dotenv

# Carga las variables de entorno desde el archivo .env
load_dotenv()

# Variables de entorno para la conexión a la base de datos y al almacén de datos
URI_ATLAS = os.environ.get('URI_ATLAS')
SNOWFLAKE_USER = os.environ.get('SNOWFLAKE_USER')
SNOWFLAKE_PASSWORD = os.environ.get('SNOWFLAKE_PASSWORD')
SNOWFLAKE_ACCOUNT = os.environ.get('SNOWFLAKE_ACCOUNT')
SNOWFLAKE_WAREHOUSE = os.environ.get('SNOWFLAKE_WAREHOUSE')
SNOWFLAKE_DATABASE = os.environ.get('SNOWFLAKE_DATABASE')
SNOWFLAKE_SCHEMA = os.environ.get('SNOWFLAKE_SCHEMA')

# Rutas a las carpetas que contienen los archivos JSON de datos de fútbol
COMPETITIONS_FOLDER = './data/input_competiciones'
MATCHES_FOLDER = './data/input_partidos'
EVENTS_FOLDER = './data/input_eventos'


# ============================================================================
#                          FUNCIONES DE LOGGING
# ============================================================================
def setup_logging():
    """Configura el sistema de logging para el pipeline.
    Los logs se escribirán en un archivo y en la consola (stderr).
    """
    log_dir = 'logs'
    log_file = os.path.join(log_dir, 'pipeline.log')

    # Crea el directorio 'logs' si no existe
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO) # Establecer el nivel mínimo de registro a INFO

    # Eliminar cualquier handler existente para evitar duplicados en entornos como Colab
    for handler in list(logger.handlers):
        logger.removeHandler(handler)
        logger.close() # Es importante cerrar los handlers, especialmente los de archivo

    # Crear manejador de archivo para guardar los logs
    file_handler = logging.FileHandler(log_file, mode='a') # Modo de añadir al final del archivo
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    logger.addHandler(file_handler)

    # Crear manejador de consola para mostrar los logs en stderr
    console_handler = logging.StreamHandler(sys.stderr)
    console_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    logger.addHandler(console_handler)

    logger.info("Configuración de logging iniciada.")
    return logger

# Obtiene la instancia del logger
logger = logging.getLogger(__name__)

# Esto es para evitar la reconfiguración en Colab si la celda se ejecuta múltiples veces
if not logger.handlers:
    logger = setup_logging()

# ============================================================================
#                          FUNCIONES DE INGESTA (MONGODB)
# ============================================================================
def get_mongo_client(uri: str):
    """Establece la conexión con MongoDB Atlas y devuelve el cliente y la base de datos."""
    start_time = time.time()
    logger.info("Conectando a MongoDB Atlas...")
    try:
        client = MongoClient(uri)
        db = client['TFM_Scouting'] # Selecciona la base de datos 'TFM_Scouting'
        logger.info(f"Conexión a MongoDB Atlas establecida con éxito. Duración: {time.time() - start_time:.2f} segundos")
        return client, db
    except Exception as e:
        logger.critical(f"Error CRÍTICO al conectar con MongoDB Atlas: {e}")
        raise # Re-lanza la excepción para detener la ejecución del pipeline

def ingest_competitions(db, folder_path: str):
    """Ingesta datos de competiciones en MongoDB buscando todos los JSON en la carpeta especificada."""
    start_time = time.time()
    coleccion_competiciones = db['competiciones'] # Accede a la colección 'competiciones'
    logger.info(f"Iniciando ingesta de competiciones desde la carpeta: {folder_path}")
    try:
        coleccion_competiciones.delete_many({}) # Elimina documentos existentes en la colección
        logger.info("Datos previos de competiciones eliminados (si existían).")

        # Busca todos los archivos JSON en la carpeta de competiciones
        archivos_competiciones = glob.glob(os.path.join(folder_path, "*.json"))
        if not archivos_competiciones:
            logger.warning(f"No se encontraron archivos JSON en la carpeta de competiciones: {folder_path}")
            return

        # Lee y inserta cada archivo JSON en la colección
        for filepath in archivos_competiciones:
            with open(filepath, encoding='utf-8') as f:
                datos = json.load(f)
            coleccion_competiciones.insert_many(datos)
            logger.info(f"Archivo '{filepath}' cargado con éxito.")

        count = coleccion_competiciones.count_documents({}) # Cuenta el total de documentos insertados
        logger.info(f"¡Éxito! Se han insertado {count} competiciones en tu base de datos. Duración: {time.time() - start_time:.2f} segundos")
    except Exception as e:
        logger.error(f"Error al insertar competiciones en MongoDB: {e}")
        raise

def ingest_matches(db, folder_path: str):
    """Ingesta datos de partidos en MongoDB buscando todos los JSON en la carpeta especificada."""
    start_time = time.time()
    coleccion_partidos = db['partidos'] # Accede a la colección 'partidos'
    logger.info(f"Iniciando ingesta de partidos desde la carpeta: {folder_path}")
    try:
        coleccion_partidos.delete_many({}) # Elimina documentos existentes en la colección
        logger.info("Datos previos de partidos eliminados (si existían).")

        # Busca todos los archivos JSON en la carpeta de partidos
        archivos_partidos = glob.glob(os.path.join(folder_path, "*.json"))
        if not archivos_partidos:
            logger.warning(f"No se encontraron archivos JSON en la carpeta de partidos: {folder_path}")
            return []

        todos_los_partidos = [] # Lista para almacenar todos los datos de partidos
        # Lee y inserta cada archivo JSON en la colección
        for filepath in archivos_partidos:
            with open(filepath, encoding='utf-8') as f:
                datos = json.load(f)
            coleccion_partidos.insert_many(datos)
            todos_los_partidos.extend(datos) # Añade los datos a la lista
            logger.info(f"Archivo '{filepath}' (partidos) cargado con éxito.")

        count = coleccion_partidos.count_documents({}) # Cuenta el total de documentos insertados
        logger.info(f"¡Éxito! Se han insertado {count} partidos en tu base de datos. Duración: {time.time() - start_time:.2f} segundos")
        return todos_los_partidos # Retorna los datos de partidos para usar en la ingesta de eventos
    except Exception as e:
        logger.error(f"Error al cargar partidos desde '{folder_path}' o insertar partidos: {e}")
        raise

def ingest_events(db, partidos: list, folder_path: str):
    """Ingesta datos de eventos en MongoDB para cada partido, buscando el archivo JSON correspondiente."""
    start_time = time.time()
    coleccion_eventos = db['eventos'] # Accede a la colección 'eventos'
    logger.info("Iniciando ingesta masiva de eventos de la temporada.")
    try:
        coleccion_eventos.delete_many({}) # Elimina documentos existentes en la colección
        logger.info("Datos previos de eventos eliminados (si existían).")

        eventos_totales_insertados = 0
        # Itera sobre cada partido para encontrar sus eventos correspondientes
        for partido in partidos:
            match_id = str(partido['match_id']) # Obtiene el ID del partido
            archivo_json = os.path.join(folder_path, f"{match_id}.json") # Construye la ruta al archivo de eventos

            if os.path.exists(archivo_json):
                try:
                    with open(archivo_json, encoding='utf-8') as file:
                        eventos = json.load(file)
                    for evento in eventos:
                        evento['match_id'] = match_id # Añade el ID del partido a cada evento
                    coleccion_eventos.insert_many(eventos) # Inserta los eventos del partido
                    eventos_totales_insertados += len(eventos)
                    logger.info(f"Partido {match_id} ingerido. ({len(eventos)} eventos)")
                except Exception as e:
                    logger.error(f"Error al procesar o insertar eventos para el partido {match_id}: {e}")
            else:
                logger.warning(f"Archivo {archivo_json} no encontrado en {folder_path}. Saltando este partido.")
        logger.info(f"RESUMEN: Total de {eventos_totales_insertados} eventos inyectados en MongoDB Atlas. Duración: {time.time() - start_time:.2f} segundos")
    except Exception as e:
        logger.error(f"Error durante la ingesta masiva de eventos: {e}")
        raise

# ============================================================================
#                        FUNCIONES DE PROCESAMIENTO (PANDAS)
# ============================================================================
def infer_position_from_coordinates(x, y):
    """Infiere una posición de jugador aproximada basada en las coordenadas (x, y) del campo.
    Las coordenadas se mapean a zonas del campo para determinar la posición.
    """
    # Si las coordenadas son nulas, retorna None
    if pd.isna(x) or pd.isna(y):
        return None

    # Portero (coordenada x menor a 10)
    if x < 10:
        return 'Goalkeeper' # Portero

    # Tercio defensivo (10 <= x < 40)
    elif 10 <= x < 40:
        if y < 20: # Banda izquierda
            return 'Left Back' # Lateral izquierdo (simplificado, podría ser carrilero izquierdo)
        elif y > 60: # Banda derecha
            return 'Right Back' # Lateral derecho (simplificado, podría ser carrilero derecho)
        else: # Defensa central
            return 'Center Back' # Central (simplificado, podría ser central izquierdo/derecho)

    # Tercio medio (40 <= x < 80)
    elif 40 <= x < 80:
        # Mediocampo defensivo (40 <= x < 55)
        if 40 <= x < 55:
            if y < 25: return 'Left Defensive Midfield' # Mediocentro defensivo izquierdo
            elif y > 55: return 'Right Defensive Midfield' # Mediocentro defensivo derecho
            else: return 'Center Defensive Midfield' # Mediocentro defensivo central
        # Mediocampo central (55 <= x < 70)
        elif 55 <= x < 70:
            if y < 25: return 'Left Midfield' # Interior izquierdo (o mediocentro izquierdo)
            elif y > 55: return 'Right Midfield' # Interior derecho (o mediocentro derecho)
            else: return 'Center Midfield' # Mediocentro central (o mediocentro izquierdo/derecho)
        # Mediocampo ofensivo (70 <= x < 80)
        else: # 70 <= x < 80
            if y < 25: return 'Left Attacking Midfield' # Mediocentro ofensivo izquierdo
            elif y > 55: return 'Right Attacking Midfield' # Mediocentro ofensivo derecho
            else: return 'Center Attacking Midfield' # Mediocentro ofensivo central

    # Tercio ofensivo (x >= 80)
    else: # x >= 80
        if y < 20: # Banda izquierda
            return 'Left Wing' # Extremo izquierdo (podría ser delantero centro izquierdo)
        elif y > 60: # Banda derecha
            return 'Right Wing' # Extremo derecho (podría ser delantero centro derecho)
        else: # Ataque central
            return 'Center Forward' # Delantero centro

    return None # Retorno por defecto, aunque todas las condiciones deberían estar cubiertas

def load_events_from_mongo_to_pandas(db) -> pd.DataFrame:
    """Carga eventos desde MongoDB a un DataFrame de Pandas, incluyendo toda la metadata de tiro para xA.
    Proyecta solo los campos necesarios para optimizar la carga.
    """
    start_time = time.time()
    logger.info("Iniciando carga de eventos desde MongoDB a Pandas.")
    coleccion = db['eventos'] # Accede a la colección 'eventos'
    event_data = [] # Lista para almacenar los documentos de eventos
    # Define la proyección para incluir solo los campos relevantes
    projection = {"_id": 0, "id": 1, "match_id": 1, "minute": 1, "second": 1, "possession": 1,
                  "type": 1, "team": 1, "player": 1, "location": 1, "period": 1, "timestamp": 1,
                  "possession_team": 1, "play_pattern": 1, "shot": 1, "carry": 1, "tactics": 1, "position": 1, "pass": 1, "dribble": 1, "pressure": 1, "duel": 1, "interception": 1, "block": 1, "clearance": 1}
    try:
        # Itera sobre los documentos de la colección y los añade a la lista
        for doc in coleccion.find({}, projection):
            event_data.append(doc)
        df_pandas = pd.DataFrame(event_data) # Crea el DataFrame de Pandas
        logger.info(f"¡Listo! Se han cargado {len(df_pandas)} registros en un DataFrame de Pandas. Duración: {time.time() - start_time:.2f} segundos")
        return df_pandas
    except Exception as e:
        logger.error(f"Error al descargar eventos de MongoDB o crear DataFrame: {e}")
        raise

def clean_and_normalize_data(df_pandas: pd.DataFrame) -> pd.DataFrame:
    """Limpia y normaliza el DataFrame de Pandas, extrayendo datos anidados y renombrando columnas.
    Convierte estructuras anidadas (diccionarios, listas) en columnas planas.
    """
    start_time = time.time()
    logger.info("Iniciando limpieza y normalización de datos.")
    df_cleaned = df_pandas.copy() # Crea una copia del DataFrame original
    try:
        # Extrae el nombre del tipo de evento del diccionario 'type'
        df_cleaned['type_name'] = df_cleaned['type'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)
        # Extrae el nombre del equipo del diccionario 'team'
        df_cleaned['team_name'] = df_cleaned['team'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)
        # Extrae el nombre del jugador del diccionario 'player'
        df_cleaned['player_name'] = df_cleaned['player'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)
        # Extrae la coordenada X de la lista 'location'
        df_cleaned['location_x'] = df_cleaned['location'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)
        # Extrae la coordenada Y de la lista 'location'
        df_cleaned['location_y'] = df_cleaned['location'].apply(lambda x: x[1] if isinstance(x, list) and len(x) > 1 else None)

        # Selecciona y renombra las columnas a español directamente
        df_limpio = df_cleaned[[
            'id', 'match_id', 'minute', 'second', 'type_name', 'team_name', 'player_name', 'location_x', 'location_y'
        ]].copy()
        df_limpio.columns = [
            'ID_EVENTO', 'ID_PARTIDO', 'MINUTO', 'SEGUNDO', 'TIPO_EVENTO', 'NOMBRE_EQUIPO', 'NOMBRE_JUGADOR', 'UBICACION_X', 'UBICACION_Y'
        ]

        logger.info(f"Limpieza y normalización de datos (df_limpio) completadas. Duración: {time.time() - start_time:.2f} segundos")
        return df_limpio
    except Exception as e:
        logger.error(f"Error durante la limpieza y normalización de datos: {e}")
        raise

def perform_tactical_feature_engineering(df_limpio: pd.DataFrame) -> pd.DataFrame:
    """Añade características tácticas al DataFrame limpio, como la zona y el carril del campo.
    También crea una bandera para acciones en zona de creación/peligro.
    """
    start_time = time.time()
    logger.info("Iniciando feature engineering táctico.")
    df_tactico = df_limpio.copy() # Crea una copia del DataFrame

    # Función para clasificar la zona del campo según la coordenada X
    def clasificar_zona_x(x):
        if pd.isna(x): return "Sin Ubicación"
        elif x < 40: return "1. Zona Defensiva"
        elif x < 80: return "2. Zona de Creación"
        else: return "3. Zona de Peligro / Último Tercio"

    # Función para clasificar el carril del campo según la coordenada Y
    def clasificar_carril_y(y):
        if pd.isna(y): return "Sin Ubicación"
        elif y < 26.6: return "Banda Izquierda"
        elif y < 53.3: return "Carril Central"
        else: return "Banda Derecha"

    # Aplica las funciones para crear nuevas columnas de zona y carril
    df_tactico['ZONA_CAMPO'] = df_tactico['UBICACION_X'].apply(clasificar_zona_x)
    df_tactico['CARRIL_CAMPO'] = df_tactico['UBICACION_Y'].apply(clasificar_carril_y)
    # Crea una bandera si la acción ocurre en una zona de creación o peligro y es un pase
    df_tactico['ES_ZONA_CREACION_PELIGRO'] = df_tactico.apply(
        lambda row: 1 if (not pd.isna(row['UBICACION_X']) and row['UBICACION_X'] > 102 and row['TIPO_EVENTO'] == 'Pass') else 0,
        axis=1
    )
    logger.info(f"Transformación táctica avanzada completada. Duración: {time.time() - start_time:.2f} segundos")
    return df_tactico

def generate_pass_networks(df_tactico: pd.DataFrame) -> pd.DataFrame:
    """Genera la red de pases a partir del DataFrame táctico.
    Identifica pases exitosos entre jugadores del mismo equipo y calcula el peso de las conexiones.
    """
    start_time = time.time()
    logger.info("Iniciando generación de redes de pases.")
    df = df_tactico.copy() # Crea una copia del DataFrame

    # Ordena los eventos para identificar secuencias de pases
    df = df.sort_values(by=['ID_PARTIDO', 'MINUTO', 'SEGUNDO']).reset_index(drop=True)
    # Desplaza columnas para identificar el siguiente jugador, equipo y partido en la secuencia
    df['SIGUIENTE_NOMBRE_JUGADOR'] = df['NOMBRE_JUGADOR'].shift(-1)
    df['SIGUIENTE_NOMBRE_EQUIPO'] = df['NOMBRE_EQUIPO'].shift(-1)
    df['SIGUIENTE_ID_PARTIDO'] = df['ID_PARTIDO'].shift(-1)

    # Filtra para obtener solo los pases exitosos entre diferentes jugadores del mismo equipo y partido
    df_pases_exitosos = df[
        (df['TIPO_EVENTO'] == 'Pass') & # El evento debe ser un pase
        (df['SIGUIENTE_NOMBRE_JUGADOR'].notnull()) & # Debe haber un siguiente jugador
        (df['ID_PARTIDO'] == df['SIGUIENTE_ID_PARTIDO']) & # El pase debe ser dentro del mismo partido
        (df['NOMBRE_EQUIPO'] == df['SIGUIENTE_NOMBRE_EQUIPO']) & # El pase debe ser entre jugadores del mismo equipo
        (df['NOMBRE_JUGADOR'] != df['SIGUIENTE_NOMBRE_JUGADOR']) # El pasador y el receptor deben ser diferentes
    ].copy()
    logger.info(f"Filtrado de pases exitosos completado. {len(df_pases_exitosos)} pases detectados.")

    # Agrupa por equipo, pasador y receptor para contar el número de pases (peso de la conexión)
    matriz_conexiones = df_pases_exitosos.groupby(
        ['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR', 'SIGUIENTE_NOMBRE_JUGADOR']
    ).size().reset_index(name='PESO_CONEXION')

    # Renombra la columna para mayor claridad
    matriz_conexiones = matriz_conexiones.rename(columns={'SIGUIENTE_NOMBRE_JUGADOR': 'RECEPTOR_JUGADOR'})
    logger.info(f"Matriz de conexiones de pases generada y renombrada. Duración: {time.time() - start_time:.2f} segundos")
    return matriz_conexiones.sort_values(by='PESO_CONEXION', ascending=False) # Ordena por peso de conexión descendente

def detect_outliers(df_kpis: pd.DataFrame) -> pd.DataFrame:
    """Detecta jugadoras de élite (Outliers) iterando por macro-posición y usando métricas P90."""
    start_time = time.time()
    logger.info("Iniciando detección de anomalías segmentada por posición (P90).")

    # Filtro de ruido: Solo jugadoras con más de 90 minutos jugados
    df = df_kpis[df_kpis['MINUTOS_JUGADOS'] >= 90].copy()

    # 1. Agrupar por Macro-Posiciones tácticas
    def mapear_macro_posicion(pos):
        defensas = ['Center Back', 'Left Back', 'Right Back']
        medios = ['Left Defensive Midfield', 'Right Defensive Midfield', 'Center Defensive Midfield',
                  'Left Midfield', 'Right Midfield', 'Center Midfield',
                  'Left Attacking Midfield', 'Right Attacking Midfield', 'Center Attacking Midfield']
        atacantes = ['Left Wing', 'Right Wing', 'Center Forward']

        if pos in defensas: return 'Defensa'
        elif pos in medios: return 'Mediocentro'
        elif pos in atacantes: return 'Delantero'
        else: return 'Portero'

    df['MACRO_POSICION'] = df['POSICION_PRINCIPAL'].apply(mapear_macro_posicion)

    # 2. Calcular métricas por 90 minutos (P90)
    factor90 = 90 / df['MINUTOS_JUGADOS']
    df['RECUPERACIONES_P90'] = (df['INTERCEPCIONES'] + df['ENTRADAS_EXITOSAS']) * factor90
    df['DESPEJES_P90'] = df['DESPEJES'] * factor90
    df['PASES_COMPLETADOS_P90'] = df['PASES_COMPLETADOS'] * factor90
    df['XA_P90'] = df['XA_ACUMULADO'] * factor90
    df['XG_P90'] = df['XG_ACUMULADO'] * factor90
    df['TIROS_P90'] = df['TIROS_INTENTADOS'] * factor90
    df['PASES_PELIGRO_P90'] = df['PASES_ZONA_PELIGRO'] * factor90

    # 3. Iterar modelo de Machine Learning por línea
    resultados = []
    for posicion in ['Defensa', 'Mediocentro', 'Delantero']:
        df_pos = df[df['MACRO_POSICION'] == posicion].copy()

        if len(df_pos) < 10: # Evitar errores si hay pocos datos
            continue

        # Seleccionar features específicas según el rol
        if posicion == 'Defensa':
            features = ['RECUPERACIONES_P90', 'DESPEJES_P90', 'EFICIENCIA_PASES_%']
        elif posicion == 'Mediocentro':
            features = ['PASES_COMPLETADOS_P90', 'XA_P90', 'EFICIENCIA_PASES_%']
        else: # Delantero
            features = ['XG_P90', 'TIROS_P90', 'PASES_PELIGRO_P90']

        # Entrenar el modelo solo con su grupo
        X = df_pos[features].fillna(0)
        modelo = IsolationForest(contamination=0.06, random_state=42) # 6% de élite por posición
        df_pos['ANOMALIA_SCORE'] = modelo.fit_predict(X)

        df_pos['ESTADO_JUGADOR'] = df_pos.apply(
            lambda row: f"Élite ({posicion})" if row['ANOMALIA_SCORE'] == -1 else 'Estándar',
            axis=1
        )
        resultados.append(df_pos)
        logger.info(f"Modelo Isolation Forest entrenado para {posicion}.")

    df_final_outliers = pd.concat(resultados) if resultados else pd.DataFrame()
    logger.info(f"Detección de anomalías finalizada. Duración: {time.time() - start_time:.2f} segundos")

    return df_final_outliers

def extract_advanced_features_pro(df_pandas: pd.DataFrame) -> pd.DataFrame:
    """Extrae características avanzadas, incluyendo cálculo de xA (Expected Assists) mapeando key_pass_id de los tiros.
    Procesa cada evento para construir un DataFrame con métricas detalladas.
    """
    start_time = time.time()
    logger.info("Iniciando extracción y procesamiento avanzado de datos de eventos (df_pro).")

    # 1. Precomputar un mapa de xG por cada ID de pase clave (key_pass_id) a partir de los tiros
    # Esto se hace para poder asignar el xG de un tiro a la asistencia clave que lo generó (xA)
    key_pass_xg_map = {}
    for _, row in df_pandas.iterrows():
        type_data = row.get('type')
        tipo = type_data.get('name') if isinstance(type_data, dict) else None
        if tipo == 'Shot': # Si el evento es un tiro
            shot_info = row.get('shot', {}) # Obtiene la información del tiro
            if isinstance(shot_info, dict):
                key_pass_id = shot_info.get('key_pass_id') # Obtiene el ID del pase clave
                if key_pass_id:
                    xg_val = float(shot_info.get('statsbomb_xg', 0.0) or 0.0) # Obtiene el xG del tiro
                    # Si múltiples tiros apuntaran al mismo key_pass_id, acumulamos o asignamos
                    key_pass_xg_map[key_pass_id] = key_pass_xg_map.get(key_pass_id, 0.0) + xg_val

    datos_avanzados = [] # Lista para almacenar los registros procesados
    # Itera sobre cada fila del DataFrame de eventos para extraer características
    for idx, row in df_pandas.iterrows():
        # Extrae el tipo de evento, equipo, jugador, ID del partido, ID del evento y ubicación
        type_data = row.get('type')
        tipo = type_data.get('name') if isinstance(type_data, dict) else None

        team_data = row.get('team')
        team = team_data.get('name') if isinstance(team_data, dict) else None

        player_data = row.get('player')
        player = player_data.get('name') if isinstance(player_data, dict) else None

        match_id = row.get('match_id')
        event_id = row.get('id')
        loc = row.get('location')

        # Inicializa un diccionario con las métricas para el evento actual
        reg = {
            'ID_PARTIDO': match_id,
            'NOMBRE_EQUIPO': team,
            'NOMBRE_JUGADOR': player,
            'TIPO_EVENTO': tipo,
            'UBICACION_X': loc[0] if isinstance(loc, list) and len(loc) > 0 else None,
            'UBICACION_Y': loc[1] if isinstance(loc, list) and len(loc) > 1 else None,
            'RESULTADO_PASE': None,
            'ASISTENCIA_GOL_PASE': 0,
            'ASISTENCIA_TIRO_PASE': 0,
            'PASE_XA': 0.0,  # Nuevo campo xA (Expected Assists)
            'TIRO_XG': 0.0,
            'RESULTADO_TIRO': None,
            'CONDUCCION_FIN_X': None,
            'CONDUCCION_FIN_Y': None,
            'CONDUCCION_DISTANCIA': 0.0,
            'PASE_INTENTADO': 0,
            'PASE_EXITOSO': 0,
            'TIROS_INTENTADOS': 0,  # Nuevo campo para tiros totales intentados
            'GOL_MARCADO': 0,
            'RESULTADO_REGATE': None,
            'PRESIONES_INTENTADAS': 0,
            'PRESIONES_ULTIMO_TERCIO': 0,
            'ENTRADAS_INTENTADAS': 0,
            'ENTRADAS_EXITOSAS': 0,
            'INTERCEPCIONES': 0,
            'BLOQUEOS': 0,
            'DESPEJES': 0,
            # Nuevos campos para pases en zonas y dirección
            'PASES_ZONA_PELIGRO': 0,
            'PASES_ZONA_NO_PELIGRO': 0,
            'PASES_ZONA_PELIGRO_ADELANTE': 0,
            'PASES_ZONA_PELIGRO_ATRAS': 0,
            'PASES_ZONA_NO_PELIGRO_ADELANTE': 0,
            'PASES_ZONA_NO_PELIGRO_ATRAS': 0
        }

        # Lógica de procesamiento para eventos de tipo 'Pass'
        if tipo == 'Pass':
            reg['PASE_INTENTADO'] = 1 # Marca el pase como intentado
            pass_info = row.get('pass', {}) # Obtiene la información del pase
            if isinstance(pass_info, dict):
                outcome_pass = pass_info.get('outcome') # Resultado del pase
                end_loc = pass_info.get('end_location') # Ubicación final del pase

                if outcome_pass is None: # Si no hay un resultado explícito, se considera completo
                    reg['RESULTADO_PASE'] = 'Complete'
                    reg['PASE_EXITOSO'] = 1
                else:
                    out_name = outcome_pass.get('name') if isinstance(outcome_pass, dict) else str(outcome_pass)
                    reg['RESULTADO_PASE'] = out_name
                    # Si el resultado indica un pase fallido, marca PASE_EXITOSO como 0
                    if out_name in ['Incomplete', 'Out', 'Pass Offside', 'Injury', 'Unknown', 'Blocked', 'Incomplete Dangerous']:
                        reg['PASE_EXITOSO'] = 0
                    else:
                        reg['PASE_EXITOSO'] = 1

                # Clasificar pases por zona y dirección (adelante/atrás)
                if reg['UBICACION_X'] is not None and end_loc is not None and len(end_loc) > 0:
                    pass_start_x = reg['UBICACION_X'] # Coordenada X de inicio del pase
                    pass_end_x = end_loc[0] # Coordenada X de fin del pase

                    is_danger_zone = pass_start_x >= 80 # Verifica si el pase se origina en zona de peligro
                    # Define si es un pase hacia adelante o hacia atrás con un pequeño umbral
                    is_forward_pass = pass_end_x > pass_start_x + 1
                    is_backward_pass = pass_end_x < pass_start_x - 1

                    if is_danger_zone: # Si es en zona de peligro
                        reg['PASES_ZONA_PELIGRO'] = 1
                        if is_forward_pass:
                            reg['PASES_ZONA_PELIGRO_ADELANTE'] = 1
                        elif is_backward_pass:
                            reg['PASES_ZONA_PELIGRO_ATRAS'] = 1
                    else: # Si no es en zona de peligro
                        reg['PASES_ZONA_NO_PELIGRO'] = 1
                        if is_forward_pass:
                            reg['PASES_ZONA_NO_PELIGRO_ADELANTE'] = 1
                        elif is_backward_pass:
                            reg['PASES_ZONA_NO_PELIGRO_ATRAS'] = 1

                # Marca si el pase fue asistencia de gol o asistencia de tiro
                if pass_info.get('goal_assist') is True:
                    reg['ASISTENCIA_GOL_PASE'] = 1
                if pass_info.get('shot_assist') is True:
                    reg['ASISTENCIA_TIRO_PASE'] = 1
                    # Asigna xA utilizando el key_pass_id o el mapa precomputado si coincide con el event_id
                    if event_id in key_pass_xg_map:
                        reg['PASE_XA'] = key_pass_xg_map[event_id]
            else: # Si no hay información de pase detallada, asume pase completo
                reg['RESULTADO_PASE'] = 'Complete'
                reg['PASE_EXITOSO'] = 1
                # Para pases completos implícitos, no hay ubicación final, así que no se puede determinar la dirección
                if reg['UBICACION_X'] is not None:
                    if reg['UBICACION_X'] >= 80:
                        reg['PASES_ZONA_PELIGRO'] = 1
                    else:
                        reg['PASES_ZONA_NO_PELIGRO'] = 1

        # Lógica de procesamiento para eventos de tipo 'Shot'
        elif tipo == 'Shot':
            reg['TIROS_INTENTADOS'] = 1  # Conteo de tiros intentados
            shot_info = row.get('shot', {}) # Obtiene la información del tiro
            if isinstance(shot_info, dict):
                reg['TIRO_XG'] = float(shot_info.get('statsbomb_xg', 0.0) or 0.0) # Obtiene el xG del tiro
                outcome_shot = shot_info.get('outcome') # Resultado del tiro
                if isinstance(outcome_shot, dict):
                    reg['RESULTADO_TIRO'] = outcome_shot.get('name')
                elif isinstance(outcome_shot, str):
                    reg['RESULTADO_TIRO'] = outcome_shot

                if reg['RESULTADO_TIRO'] == 'Goal': # Si el resultado es gol
                    reg['GOL_MARCADO'] = 1 # Marca como gol

        # Lógica de procesamiento para eventos de tipo 'Dribble'
        elif tipo == 'Dribble':
            dribble_info = row.get('dribble', {}) # Obtiene la información del regate
            if isinstance(dribble_info, dict):
                outcome_dribble = dribble_info.get('outcome') # Resultado del regate
                if isinstance(outcome_dribble, dict):
                    reg['RESULTADO_REGATE'] = outcome_dribble.get('name')
                elif isinstance(outcome_dribble, str):
                    reg['RESULTADO_REGATE'] = outcome_dribble

        # Lógica de procesamiento para eventos de tipo 'Carry' (conducción)
        elif tipo == 'Carry':
            carry_info = row.get('carry', {}) # Obtiene la información de la conducción
            if isinstance(carry_info, dict):
                end_loc = carry_info.get('end_location') # Ubicación final de la conducción
                if isinstance(end_loc, list) and len(end_loc) >= 2:
                    reg['CONDUCCION_FIN_X'] = end_loc[0]
                    reg['CONDUCCION_FIN_Y'] = end_loc[1]
                    if reg['UBICACION_X'] is not None and reg['UBICACION_Y'] is not None:
                        # Calcula la distancia euclidiana de la conducción
                        dist = np.sqrt((end_loc[0] - reg['UBICACION_X'])**2 + (end_loc[1] - reg['UBICACION_Y'])**2)
                        reg['CONDUCCION_DISTANCIA'] = round(dist, 2)

        # Lógica de procesamiento para eventos de tipo 'Pressure'
        elif tipo == 'Pressure':
            reg['PRESIONES_INTENTADAS'] = 1 # Marca la presión como intentada
            # Si la presión ocurre en el último tercio del campo
            if reg['UBICACION_X'] is not None and reg['UBICACION_X'] > 80:
                reg['PRESIONES_ULTIMO_TERCIO'] = 1

        # Lógica de procesamiento para eventos de tipo 'Duel' (duelo)
        elif tipo == 'Duel':
            duel_info = row.get('duel', {}) # Obtiene la información del duelo
            if isinstance(duel_info, dict):
                duel_type = duel_info.get('type', {}).get('name') # Tipo de duelo
                duel_outcome = duel_info.get('outcome', {}).get('name') # Resultado del duelo
                if duel_type == 'Tackle': # Si el duelo es una entrada
                    reg['ENTRADAS_INTENTADAS'] = 1 # Marca la entrada como intentada
                    if duel_outcome in ['Won', 'Success in Play']: # Si la entrada fue exitosa
                        reg['ENTRADAS_EXITOSAS'] = 1

        # Lógica de procesamiento para eventos de tipo 'Interception'
        elif tipo == 'Interception':
            interception_info = row.get('interception', {}) # Obtiene la información de la intercepción
            if isinstance(interception_info, dict):
                interception_outcome = interception_info.get('outcome', {}).get('name') # Resultado de la intercepción
                if interception_outcome == 'Won': # Si la intercepción fue exitosa
                     reg['INTERCEPCIONES'] = 1

        # Lógica de procesamiento para eventos de tipo 'Block' (bloqueo)
        elif tipo == 'Block':
            reg['BLOQUEOS'] = 1 # Marca el bloqueo

        # Lógica de procesamiento para eventos de tipo 'Clearance' (despeje)
        elif tipo == 'Clearance':
            reg['DESPEJES'] = 1 # Marca el despeje

        datos_avanzados.append(reg) # Añade el registro de métricas a la lista

    df_pro = pd.DataFrame(datos_avanzados) # Crea el DataFrame final con características avanzadas
    logger.info(f"DataFrame df_pro creado con éxito a partir de datos avanzados de eventos. Duración: {time.time() - start_time:.2f} segundos")
    return df_pro

def calculate_final_kpis_from_pro(df_pro: pd.DataFrame) -> pd.DataFrame:
    """Calcula los KPIs finales incorporando TIROS_INTENTADOS, TASA_CONVERSION_TIRO, GOLES_MENOS_XG y XA_ACUMULADO.
    Agrupa por equipo y jugador para obtener métricas agregadas y ratios de eficiencia.
    """
    start_time = time.time()
    logger.info("Iniciando cálculo de KPIs finales (df_kpis_finales).")
    # Agrupa por equipo y jugador y agrega las métricas relevantes
    df_kpis_finales = df_pro.groupby(['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR']).agg(
        TOTAL_ACCIONES=('TIPO_EVENTO', 'count'),
        METROS_CONDUCIDOS_TOTALES=('CONDUCCION_DISTANCIA', 'sum'),
        PASES_INTENTADOS=('PASE_INTENTADO', 'sum'),
        PASES_COMPLETADOS=('PASE_EXITOSO', 'sum'),
        # Agregados para pases en zonas
        PASES_ZONA_PELIGRO=('PASES_ZONA_PELIGRO', 'sum'),
        PASES_ZONA_NO_PELIGRO=('PASES_ZONA_NO_PELIGRO', 'sum'),
        # Nuevos agregados para pases en zonas y dirección
        PASES_ZONA_PELIGRO_ADELANTE=('PASES_ZONA_PELIGRO_ADELANTE', 'sum'),
        PASES_ZONA_PELIGRO_ATRAS=('PASES_ZONA_PELIGRO_ATRAS', 'sum'),
        PASES_ZONA_NO_PELIGRO_ADELANTE=('PASES_ZONA_NO_PELIGRO_ADELANTE', 'sum'),
        PASES_ZONA_NO_PELIGRO_ATRAS=('PASES_ZONA_NO_PELIGRO_ATRAS', 'sum'),
        TIROS_INTENTADOS=('TIROS_INTENTADOS', 'sum'),
        GOLES_REALES=('GOL_MARCADO', 'sum'),
        XG_ACUMULADO=('TIRO_XG', 'sum'),
        XA_ACUMULADO=('PASE_XA', 'sum'),
        ASISTENCIAS_GOL=('ASISTENCIA_GOL_PASE', 'sum'),
        ASISTENCIAS_TIRO=('ASISTENCIA_TIRO_PASE', 'sum'),
        REGATES_INTENTADOS=('RESULTADO_REGATE', lambda x: (x.notnull()).sum()), # Cuenta regates intentados
        REGATES_EXITOSOS=('RESULTADO_REGATE', lambda x: (x == 'Complete').sum()), # Cuenta regates exitosos
        PRESIONES_INTENTADAS=('PRESIONES_INTENTADAS', 'sum'),
        PRESIONES_ULTIMO_TERCIO=('PRESIONES_ULTIMO_TERCIO', 'sum'),
        ENTRADAS_INTENTADAS=('ENTRADAS_INTENTADAS', 'sum'),
        ENTRADAS_EXITOSAS=('ENTRADAS_EXITOSAS', 'sum'),
        INTERCEPCIONES=('INTERCEPCIONES', 'sum'),
        BLOQUEOS=('BLOQUEOS', 'sum'),
        DESPEJES=('DESPEJES', 'sum')
    ).reset_index()

    # Cálculos de ratios y eficiencias
    df_kpis_finales['EFICIENCIA_PASES_%'] = np.where(
        df_kpis_finales['PASES_INTENTADOS'] > 0,
        round((df_kpis_finales['PASES_COMPLETADOS'] / df_kpis_finales['PASES_INTENTADOS']) * 100, 2),
        0.0
    )
    df_kpis_finales['EFICIENCIA_REGATES_%'] = np.where(
        df_kpis_finales['REGATES_INTENTADOS'] > 0,
        round((df_kpis_finales['REGATES_EXITOSOS'] / df_kpis_finales['REGATES_INTENTADOS']) * 100, 2),
        0.0
    )
    df_kpis_finales['EFICIENCIA_ENTRADAS_%'] = np.where(
        df_kpis_finales['ENTRADAS_INTENTADAS'] > 0,
        round((df_kpis_finales['ENTRADAS_EXITOSAS'] / df_kpis_finales['ENTRADAS_INTENTADAS']) * 100, 2),
        0.0
    )

    # 1. Tasa de conversión de tiro (Goles / Tiros)
    df_kpis_finales['TASA_CONVERSION_TIRO_%'] = np.where(
        df_kpis_finales['TIROS_INTENTADOS'] > 0,
        round((df_kpis_finales['GOLES_REALES'] / df_kpis_finales['TIROS_INTENTADOS']) * 100, 2),
        0.0
    )

    # 2. Diferencial de finalización o Goles Menos xG (Goles - xG)
    df_kpis_finales['GOLES_MENOS_XG'] = round(df_kpis_finales['GOLES_REALES'] - df_kpis_finales['XG_ACUMULADO'], 2)

    df_kpis_finales = df_kpis_finales.sort_values(by='XG_ACUMULADO', ascending=False) # Ordena por xG acumulado
    logger.info(f"KPIs finales calculados con éxito. Duración: {time.time() - start_time:.2f} segundos")
    return df_kpis_finales

def integrate_player_positions_to_kpis(df_kpis_finales: pd.DataFrame, df_pandas: pd.DataFrame, df_pro: pd.DataFrame) -> pd.DataFrame:
    """Integra las posiciones de los jugadores, partidos de titular y minutos jugados a los KPIs finales,
       e infiere posiciones para 'Rotación / Suplente' basándose en la ubicación media de sus eventos.
    """
    start_time = time.time()
    logger.info("Integrando posiciones de jugadores, partidos de titular y minutos jugados a los KPIs finales.")

    df_kpis_finales_copy = df_kpis_finales.copy() # Crea una copia del DataFrame de KPIs

    # --- 1. Extraer posiciones y partidos de titular (Starting XI) ---
    # Filtra eventos de tipo 'Starting XI' para obtener las alineaciones iniciales
    starting_xi_events = df_pandas[df_pandas['type'].apply(lambda x: x.get('name') if isinstance(x, dict) else None) == 'Starting XI']
    posiciones_data = []
    for idx, row in starting_xi_events.iterrows():
        match_id = row['match_id']
        team_name = row['team'].get('name') if isinstance(row.get('team'), dict) else None
        player_name = row['player'].get('name') if isinstance(row.get('player'), dict) else None # Obtiene el nombre del jugador del evento 'Starting XI'
        tactics = row.get('tactics', {}) # Obtiene la información táctica
        if isinstance(tactics, dict) and 'lineup' in tactics:
            for player_entry in tactics['lineup']:
                player_name_lineup = player_entry.get('player', {}).get('name')
                position_name = player_entry.get('position', {}).get('name')
                if team_name and player_name_lineup and position_name:
                    posiciones_data.append({
                        'ID_PARTIDO': match_id,
                        'NOMBRE_EQUIPO': team_name,
                        'NOMBRE_JUGADOR': player_name_lineup,
                        'POSICION_PRINCIPAL': position_name
                    })
    df_pos_mapping = pd.DataFrame(posiciones_data) # Crea un DataFrame con las posiciones mapeadas

    # Calcula el número de partidos de titular para cada jugador
    df_partidos_titular = df_pos_mapping.groupby(['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR'])['ID_PARTIDO'].nunique().reset_index(name='PARTIDOS_TITULAR')
    # Conserva solo la primera posición distinta para cada jugador para 'POSICION_PRINCIPAL'
    df_pos_principal = df_pos_mapping.drop_duplicates(subset=['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR', 'POSICION_PRINCIPAL']).groupby(['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR']).first().reset_index()
    df_pos_principal = df_pos_principal[['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR', 'POSICION_PRINCIPAL']]

    # --- 2. Calcular minutos jugados ---
    df_players_events = df_pandas.copy() # Crea una copia del DataFrame de eventos
    df_players_events['NOMBRE_EQUIPO'] = df_players_events['team'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)
    df_players_events['NOMBRE_JUGADOR'] = df_players_events['player'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)

    # Calcula el minuto máximo jugado por cada jugador en cada partido
    df_minutes = df_players_events.groupby(['match_id', 'NOMBRE_EQUIPO', 'NOMBRE_JUGADOR'])['minute'].max().reset_index()
    df_minutes = df_minutes.rename(columns={'minute': 'MINUTOS_MAX_PARTIDO', 'match_id': 'ID_PARTIDO'})

    # Suma los minutos jugados en todos los partidos para cada jugador
    df_total_minutes = df_minutes.groupby(['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR'])['MINUTOS_MAX_PARTIDO'].sum().reset_index(name='MINUTOS_JUGADOS')

    # --- 3. Unir toda la información a df_kpis_finales ---
    # Elimina la columna 'POSICION_PRINCIPAL' si ya existe para evitar errores en la fusión
    if 'POSICION_PRINCIPAL' in df_kpis_finales_copy.columns:
        df_kpis_finales_copy = df_kpis_finales_copy.drop(columns=['POSICION_PRINCIPAL'])

    # Fusiona el DataFrame de KPIs con las posiciones principales
    df_kpis_finales_copy = pd.merge(
        df_kpis_finales_copy,
        df_pos_principal,
        on=['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR'],
        how='left'
    )
    # Fusiona con los partidos de titular
    df_kpis_finales_copy = pd.merge(
        df_kpis_finales_copy,
        df_partidos_titular,
        on=['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR'],
        how='left'
    )
    # Fusiona con los minutos jugados
    df_kpis_finales_copy = pd.merge(
        df_kpis_finales_copy,
        df_total_minutes,
        on=['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR'],
        how='left'
    )

    # --- 4. Inferir posiciones para 'Rotación / Suplente' ---
    # Rellena los valores nulos iniciales de 'POSICION_PRINCIPAL' con 'Rotación / Suplente'
    df_kpis_finales_copy['POSICION_PRINCIPAL'] = df_kpis_finales_copy['POSICION_PRINCIPAL'].fillna('Rotación / Suplente')

    # Obtiene los jugadores que necesitan inferencia de posición
    players_to_infer = df_kpis_finales_copy[df_kpis_finales_copy['POSICION_PRINCIPAL'] == 'Rotación / Suplente']

    if not players_to_infer.empty:
        logger.info(f"Iniciando inferencia de posición para {len(players_to_infer)} jugadores con posición 'Rotación / Suplente'.")

        # Calcula la ubicación promedio (x, y) para cada jugador a partir de df_pro
        avg_locations = df_pro.groupby(['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR']).agg(
            AVG_UBICACION_X=('UBICACION_X', 'mean'),
            AVG_UBICACION_Y=('UBICACION_Y', 'mean')
        ).reset_index()

        # Unir las ubicaciones promedio con los KPIs finales para los jugadores a inferir
        df_kpis_finales_copy = pd.merge(
            df_kpis_finales_copy,
            avg_locations,
            on=['NOMBRE_EQUIPO', 'NOMBRE_JUGADOR'],
            how='left'
        )

        # Aplica la función de inferencia de posición solo a los jugadores con 'Rotación / Suplente'
        for index, row in df_kpis_finales_copy.iterrows():
            if row['POSICION_PRINCIPAL'] == 'Rotación / Suplente':
                inferred_pos = infer_position_from_coordinates(row['AVG_UBICACION_X'], row['AVG_UBICACION_Y'])
                if inferred_pos:
                    df_kpis_finales_copy.loc[index, 'POSICION_PRINCIPAL'] = inferred_pos
                    logger.debug(f"Posición inferida para {row['NOMBRE_JUGADOR']} ({row['NOMBRE_EQUIPO']}): {inferred_pos}")

        # Elimina las columnas temporales de ubicación promedio una vez que la inferencia ha terminado
        df_kpis_finales_copy = df_kpis_finales_copy.drop(columns=['AVG_UBICACION_X', 'AVG_UBICACION_Y'], errors='ignore')
        logger.info("Inferencia de posiciones completada.")

    # Rellena los valores nulos de 'PARTIDOS_TITULAR' y 'MINUTOS_JUGADOS' con 0 y convierte a entero
    df_kpis_finales_copy['PARTIDOS_TITULAR'] = df_kpis_finales_copy['PARTIDOS_TITULAR'].fillna(0).astype(int)
    df_kpis_finales_copy['MINUTOS_JUGADOS'] = df_kpis_finales_copy['MINUTOS_JUGADOS'].fillna(0).astype(int)

    logger.info(f"Posiciones, partidos de titular y minutos jugados integrados con éxito. Duración: {time.time() - start_time:.2f} segundos")
    return df_kpis_finales_copy

# ============================================================================
#                          FUNCIONES DE CARGA (SNOWFLAKE)
# ============================================================================
def upload_data_to_snowflake(dfs_to_upload: dict):
    """Carga DataFrames a Snowflake.
    Establece conexión, elimina tablas existentes y sube los DataFrames especificados.
    """
    start_time = time.time()
    logger.info("Iniciando proceso de carga a Snowflake.")
    try:
        # Establece la conexión con Snowflake utilizando las credenciales de las variables de entorno
        ctx = snowflake.connector.connect(
            user=SNOWFLAKE_USER,
            password=SNOWFLAKE_PASSWORD,
            account=SNOWFLAKE_ACCOUNT,
            warehouse=SNOWFLAKE_WAREHOUSE,
            database=SNOWFLAKE_DATABASE,
            schema=SNOWFLAKE_SCHEMA
        )
        logger.info("Conexión establecida con éxito en Snowflake!")
    except Exception as e:
        logger.critical(f"Error CRÍTICO al conectar con Snowflake: {e}")
        raise

    # Itera sobre cada DataFrame a subir
    for nombre_tabla, df in dfs_to_upload.items():
        if df.empty:
            logger.warning(f"Saltando la carga de la tabla '{nombre_tabla}' porque el DataFrame está vacío.")
            continue

        df_temp = df.copy() # Crea una copia temporal del DataFrame
        df_temp.columns = [str(col).upper() for col in df_temp.columns] # Convierte los nombres de las columnas a mayúsculas para Snowflake
        df_temp = df_temp.reset_index(drop=True) # Resetea el índice del DataFrame
        logger.info(f"Preparando la tabla '{nombre_tabla}' para la carga.")

        cursor = ctx.cursor() # Crea un cursor para ejecutar comandos SQL
        try:
            cursor.execute(f"DROP TABLE IF EXISTS {nombre_tabla}") # Elimina la tabla si ya existe
            logger.info(f"Tabla '{nombre_tabla}' borrada previamente en Snowflake (si existía).")
            # Escribe el DataFrame en Snowflake, creando la tabla automáticamente si no existe
            success, nchunks, nrows, _ = write_pandas(ctx, df_temp, nombre_tabla, auto_create_table=True)
            logger.info(f"Tabla {nombre_tabla} cargada con éxito: {nrows} filas subidas.")
        except Exception as e:
            logger.error(f"Error al subir {nombre_tabla} a Snowflake: {e}")
        finally:
            cursor.close() # Cierra el cursor
    ctx.close() # Cierra la conexión a Snowflake
    logger.info("Conexión a Snowflake cerrada.")
    logger.info(f"Proceso de carga a Snowflake completado. Duración: {time.time() - start_time:.2f} segundos")

# ============================================================================
#                          FUNCIÓN PRINCIPAL DEL PIPELINE
# ============================================================================
def run_etl_pipeline():
    """Orquesta la ejecución de todo el pipeline ETL.
    Define la secuencia de pasos: ingesta, procesamiento, cálculo de KPIs y carga a Snowflake.
    """
    pipeline_start_time = time.time()
    logger.info("===========================================================")
    logger.info("           INICIANDO EJECUCIÓN DEL PIPELINE ETL         ")
    logger.info("===========================================================")

    mongo_client = None # Inicializa el cliente de MongoDB a None
    try:
        # Conexión a MongoDB Atlas
        mongo_client, db = get_mongo_client(URI_ATLAS)

        # Ingesta de datos en MongoDB (competiciones, partidos, eventos)
        ingest_competitions(db, COMPETITIONS_FOLDER)
        partidos_data = ingest_matches(db, MATCHES_FOLDER)
        ingest_events(db, partidos_data, EVENTS_FOLDER)

        # Carga de datos de eventos desde MongoDB a Pandas y limpieza inicial
        df_pandas = load_events_from_mongo_to_pandas(db)
        df_limpio = clean_and_normalize_data(df_pandas)

        # Feature Engineering táctico y cálculos de KPIs
        df_tactico = perform_tactical_feature_engineering(df_limpio)
        df_red_final = generate_pass_networks(df_tactico)


        # Path alternativo para df_kpis_finales: extracción de características avanzadas y cálculo de KPIs finales
        df_pro = extract_advanced_features_pro(df_pandas)
        df_kpis_finales = calculate_final_kpis_from_pro(df_pro)
        # Integración de posiciones de jugadores y minutos jugados
        df_kpis_finales = integrate_player_positions_to_kpis(df_kpis_finales, df_pandas, df_pro)

        #Ejecutar el Machine Learning con los kpis integrados
        df_outliers_afin = detect_outliers(df_kpis_finales)

        # Preparar DataFrames para subir a Snowflake (KPIs, red de pases, anomalías)
        dfs_to_upload = {
            'GOLD_KPIS_JUGADORES': df_kpis_finales,
            'GOLD_RED_PASES': df_red_final,
            'GOLD_JUGADORES_ANOMALIAS': df_outliers_afin
        }

        # Cargar los DataFrames procesados a Snowflake
        upload_data_to_snowflake(dfs_to_upload)

        logger.info("===========================================================")
        logger.info(f"           PIPELINE ETL EJECUTADO CON ÉXITO. Duración total: {time.time() - pipeline_start_time:.2f} segundos")
        logger.info("===========================================================")

    except Exception as e:
        # Captura y registra cualquier error crítico que ocurra en el pipeline
        logger.critical(f"El pipeline ETL ha fallado con un error CRÍTICO: {e}", exc_info=True)
        logger.info("===========================================================")
        logger.info(f"           PIPELINE ETL FINALIZADO CON ERRORES. Duración total: {time.time() - pipeline_start_time:.2f} segundos")
        logger.info("===========================================================")
    finally:
        # Asegura que la conexión a MongoDB se cierre al finalizar el pipeline
        if mongo_client:
            mongo_client.close()
            logger.info("Conexión a MongoDB cerrada.")
        logging.shutdown() # Cierra el sistema de logging

# Punto de entrada principal para la ejecución del script
if __name__ == '__main__':
    run_etl_pipeline()
